# Generated by Django 4.2.6 on 2023-11-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=1023)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Draft"), (2, "Published"), (3, "Archived")],
                        default=1,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activity Posts",
                "db_table": "activity_posts",
            },
        ),
    ]
