# Generated by Django 4.2.6 on 2023-11-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterestTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
            options={
                "verbose_name_plural": "Interest Tags",
                "db_table": "interest_tags",
            },
        ),
        migrations.CreateModel(
            name="SymbiUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("full_name", models.CharField(max_length=50)),
                (
                    "pronouns",
                    models.IntegerField(
                        choices=[
                            (1, "He/Him"),
                            (2, "She/Her"),
                            (3, "They/Them"),
                            (4, "Other"),
                        ],
                        default=4,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("major", models.CharField(default="undeclared", max_length=100)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "interests",
                    models.ManyToManyField(
                        related_name="interests", to="symbi.interesttag"
                    ),
                ),
            ],
        ),
    ]
